# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

listChallenge_cpp <- function(nbLoops, batch, prob, method = "std") {
    .Call('_listChallenge_listChallenge_cpp', PACKAGE = 'listChallenge', nbLoops, batch, prob, method)
}

